src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $summary = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $published_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    /**
     * @var Collection<int, Tag>
     */
    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'posts')]
    private Collection $tags;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->published_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): static
    {
        $this->summary = $summary;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeImmutable $published_at): static
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): static
    {
        $this->tags->removeElement($tag);

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email', 'username'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $fullName = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(string $fullName): static
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }
}

src/Controller/User/BlogController.php
<?php

namespace App\Controller\User;

use App\Entity\Comment;
use App\Entity\Post;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\PostRepository;
use App\Repository\TagRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;

#[Route('/User/', name: 'app_user_')]
class BlogController extends AbstractController
{

    private $em;
    private $security;

    public function __construct(EntityManagerInterface $entityManager, Security $security)
    {
        $this->security = $security;
        $this->em = $entityManager;
    }

    #[Route('', name: 'index')]
    public function index(TagRepository $tagRepository, PostRepository $repository): Response
    {
        $posts = $repository->findby([], ["published_at" => "DESC"]);
        $tags = $tagRepository->findby([], ["id" => "DESC"]);
        return $this->render('User/index.html.twig', [
            'posts' => $posts,
            'tags' => $tags,
        ]);
    }


    #[Route('postsByTag{id}', name: 'postsByTag')]
    public function postsByTag($id, TagRepository $tagRepository): Response
    {
        $tag = $tagRepository->findOneBy(["id" => $id], ["id" => "DESC"]);
        $tags = $tagRepository->findMinus(["id" => $id]);
        return $this->render('User/postsByTag.html.twig', [
            'tag' => $tag,
            'tags' => $tags
        ]);
    }


    #[Route('post{id}', name: 'showPost')]
    public function showPost($id, Post $post, Request $request, CommentRepository $commentRepository): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        $comments = $commentRepository->findby(["post" => $id], ["published_at" => "DESC"]);
        // dd($post->getTags());
        if ($form->isSubmitted() && $form->isValid()) {
            if ($user = $this->security->getUser()) {
                $comment->setAuthor($user);
                $comment->setPost($post);
                $this->em->persist($comment);
                $this->em->flush();
                return $this->redirectToRoute("app_user_showPost", [
                    'id' => $post->getId(),
                    'post' => $post,
                    'comments' => $comments,
                    'form' => $form,
                ]);
            }
            return $this->redirectToRoute("app_login");
        }
        return $this->render('User/showPost.html.twig', [
            'post' => $post,
            'comments' => $comments,
            'form' => $form->createView(),
        ]);
    }
}

templates/User/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PostController!
{% endblock %}

{% block body %}
	<div class="example-wrapper">
		<div class="container-content">
			<div class="main">
				<h1>All Posts</h1>

				<div>
					{% for post in posts %}
						<div class="post-container">
							<a class="post-title" href="{{path("app_user_showPost",{id:post.id})}}">
								<h1>{{post.title|capitalize}}</h1>
							</a>
							<p>{{post.summary}}</p>
							<p>{{post.author.fullName}}
								|
								{{post.publishedAt|date("d M Y -- H:i")}}</p>
						</div>
					{% endfor %}
				</div>
			</div>
			<div class="side-bar">
				<h1>Categories</h1>
				{% if tags|length > 0 %}
					<div class="categories">
						{% for tag in tags %}
							<a href="{{path("app_user_postsByTag",{id:tag.id})}}">{{tag.name}}</a>
						{% endfor %}
					</div>
				{% else %}
					<h3>No categories available</h3>
				{% endif %}
			</div>
		</div>


	</div>
{% endblock %}

templates/User/postsByTag.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PostController!
{% endblock %}

{% block body %}
	<div class="example-wrapper">
		<div class="container-content">
			<div class="main">
				<h1>All Posts</h1>

				<div>
					{% if tag.posts|length > 0 %}
						{% for post in tag.posts %}
							<div class="post-container">
								<a class="post-title" href="{{path("app_user_showPost",{id:post.id})}}">
									<h1>{{post.title|capitalize}}</h1>
								</a>
								<p>{{post.summary}}</p>
								<p>{{post.author.fullName}}
									|
									{{post.publishedAt|date("d M Y -- H:i")}}</p>
							</div>
						{% endfor %}
					{% else %}
						<h2>No posts for this category</h2>
					{% endif %}
				</div>
			</div>
			<div class="side-bar">
				<h1>Categories</h1>
				{% if tags|length > 0 %}
					<div class="categories">
						{% for tag in tags %}
							<a href="{{path("app_user_postsByTag",{id:tag.id})}}">{{tag.name}}</a>
						{% endfor %}
					</div>
				{% else %}
					<h3>No categories available</h3>
				{% endif %}
			</div>
		</div>


	</div>
{% endblock %}

templates/User/showPost.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PostController!
{% endblock %}

{% block body %}
	<div class="example-wrapper">
		<h1>{{post.title}}</h1>
		<div class="tags-container">
			<h3>Tags :</h3>
			{% if post.tags|length > 0 %}
				{% for tag in post.tags %}
					<div class="tag">
						{{tag.name}}
					</div>
				{% endfor %}
			{% else %}
				<h3>No tags</h3>
			{% endif %}

		</div>
		<div>
			<div class="post-container">
				<p>{% apply markdown_to_html %}{{post.content}}{% endapply %}</p>
				<p>Published by |
					{{post.author.fullName}}
					|
					{{post.publishedAt|date("d M Y -- H:i")}}
				</p>
				{% if post.updatedAt != null %}
					<p>Updated at |
						{{post.updatedAt|date("d M Y -- H:i")}}
					</p>
				{% endif %}
				<h5>{{post.slug}}</h5>
			</div>
			{% if app.user %}
				<div class="comment-form">
					<h2>Write a comment</h2>
					{{ form_start(form) }}
					<div class="row">
						{{ form_label(form.content) }}
						{{ form_widget(form.content) }}
						{{ form_errors(form.content) }}
					</div>
					<button class="btn btn-edit" type="submit" class="btn btn-create">Share</button>
					{{ form_end(form) }}
				</div>
			{% endif %}
			<div class="comment-section">
				<h1>Comment section</h1>
				{% if  comments|length > 0 %}
					{% for comment in comments %}
						<div class="comment">
							<h3>@
								{{comment.author.username}}</h3>
							<p>{{comment.content}}</p>
							<p>Published |
								{{comment.publishedAt|date("d M Y -- H:i")}}
							</p>
						</div>
					{% endfor %}
				{% else %}
					<div class="comment">
						<h2>No comments to display</h2>
					</div>
				{% endif %}

			</div>
		</div>
	</div>
{% endblock %}